version: '1.0'
stages:
  - prepare
  - test
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: master
    git: github
  ToolsDockerImage:    # TODO:  would move this too another pipeline
    title: Building Docker Image for AWS Cli, jq, yq, etc.
    type: build
    stage: prepare
    image_name: tools
    working_directory: ./
    tag: 'non-multi-stage'
    dockerfile: Dockerfile-aws
  CreateAWSCredentialsFile:
    stage: prepare
    image: alpine
    title: Creating AWS Credentials File...
    working_directory: ${{main_clone}}
    commands:
      - mkdir -p ${CF_VOLUME_PATH}/.aws
      - 'echo -n $AWS_CREDENTIALS_FILE | base64 -d > ${CF_VOLUME_PATH}/.aws/credentials'
      - wc -l ${CF_VOLUME_PATH}/.aws/credentials
      - cf_export AWS_SHARED_CREDENTIALS_FILE=${CF_VOLUME_PATH}/.aws/credentials
  publish_blueprint:
    title: Publish the blueprint for checking
    stage: prepare
    image:  "${{ToolsDockerImage}}"
    commands:
    - cat blueprint.yml
    - jq -n --arg authorEmails "${{CF_COMMIT_AUTHOR}}" --arg version "${{CF_BUILD_ID}}" --arg triggerUrl "${{CF_COMMIT_URL}}" --arg triggerRev "${{CF_REVISION}}" --argjson blueprint "`yq -c . blueprint.yml`" -f blueprint-version-jq.config >blueprint-version.json
    - aws s3 cp blueprint-version.json s3://${BLUEPRINT_VERSION_BUCKET}/blueprints/${{CF_REPO_NAME}}/${{CF_BRANCH}}/${{CF_SHORT_REVISION}}
    - aws s3 presign s3://${BLUEPRINT_VERSION_BUCKET}/blueprints/${{CF_REPO_NAME}}/${{CF_BRANCH}}/${{CF_SHORT_REVISION}} >blueprint-version-url
  check_blueprint:
    title: Check the blueprint
    stage: prepare
    image:  "${{ToolsDockerImage}}"
    commands:
    #                       sessionid    phase    build#             triggerRev          triggerUrl        buildSnap  blueprint                    system  TODO make loop for each system?       BP Version URL
    - ./sysps-job-start.sh $FSSESSIONID "check" "${{CF_BUILD_ID}}" "${{CF_REVISION}}" "${{CF_COMMIT_URL}}" "null" `yq -r '.|.name' blueprint.yml` `yq -r '.|.deploy|keys|.[0]' blueprint.yml` `cat blueprint-version-url`
  MyUnitTests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package

