version: '1.0'
stages:
  - prepare
  - test
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: master
    git: github
  AwsDockerImage:
    title: Building Docker Image for AWS Cli
    type: build
    stage: prepare
    image_name: aws-cli
    working_directory: ./
    tag: 'non-multi-stage'
    dockerfile: Dockerfile-aws
  CreateAWSCredentialsFile:
    stage: test
    image: ${{AwsDockerImage}}
    title: Creating AWS Credentials File...
    working_directory: ${{main_clone}}
    commands:
      - mkdir -p ${CF_VOLUME_PATH}/.aws
      - 'echo -n $AWS_CREDENTIALS_FILE | base64 -d > ${CF_VOLUME_PATH}/.aws/credentials'
      - cf_export AWS_SHARED_CREDENTIALS_FILE=${CF_VOLUME_PATH}/.aws/credentials
  check_blueprint:
    title: Check the blueprint for each system
    stage: test
    image: alpine
    commands:
    - ls -altr
    - cat blueprint.yml
    - aws sts get-caller-identity
  MyUnitTests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package

