FROM python:3.8.0-alpine3.10

ENV AWSCLI_VERSION "1.16.266"
ENV JQ_VERSION "1.6-r0"
ENV YQ_VERSION "2.7.2"

# Install jq and yq for JSON / YAML parsing

RUN apk add --update jq=${JQ_VERSION} \
  && rm -rf /var/cache/apk/*

# Install AWS CLI

RUN pip install --no-cache-dir awscli==${AWSCLI_VERSION} yq==${YQ_VERSION}

LABEL alpine="3.10"
LABEL jq="${JQ_VERSION}"
LABEL yq="${YQ_VERSION}"
LABEL python="3.8.0"
LABEL aws-cli="${AWSCLI_VERSION}"

VOLUME /root/.aws
